  
version: "3"
services:
  redis:
    image: redis
    networks: 
      - webnet
  db:
    image: postgres
    networks: 
      - webnet
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  web:
    image: slack-clone-server
    ports:
      - "8081:8081"
    networks:
      - webnet
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    command: ["./wait-for-it.sh", "db:5432", "--", "node", "index.js"]
networks:
  webnet: